name: CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: All things angular
        uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.3.2
        with:
          github_access_token: ${{ secrets.ACCESS_TOKEN }}
          build_configuration: staging
          base_href: /pokeapi/
          deploy_branch: gh-pages 
          angular_project_dir: pokeapi
          angular_dist_build_folder: dist/pokeapi
